services:
  frontend:  # ← base 側のサービス名と一致させる
    build:
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    command: >
      sh -lc "if [ ! -d node_modules ]; then npm ci; fi; npm run dev"
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
  api:
    build:
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./api:/app
      - go-mod:/go/pkg/mod    # 依存キャッシュ（任意）
      - go-build:/root/.cache/go-build
    environment:
      - GO111MODULE=on
      - CGO_ENABLED=0
    # air を使う例（後述の .air.toml を用意）
    #working_dir: /src
    #command: sh -c "air -c .air.toml"
volumes:
  node_modules:
  go-mod:
  go-build: