services:
  frontend:  # ← base 側のサービス名と一致させる
    build:
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    command: >
      sh -lc "if [ ! -d node_modules ]; then npm ci; fi; npm run dev"
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
  api:
    build:
      target: dev
volumes:
  node_modules:
  go-mod:
  go-build: